---
title: "Current Research Interests"
author: "Brian Anderson"
date: "5/4/2018"
output: html_document
---

## Current Projects

- Dealing with endogeneity
- Two software development projects
    - lavaanTable
    - Moderation visualization app
- Entrepreneurial intentions
- Unemployment and entrepreneurial activity
- Increasing transparency and reproducibility in entrepreneurship research
- Entrepreneurial orientation
- Strategic and entrepreneurial leadership


## Things I Am Good At...

- Latent variable structural equation modeling
- Measurement model evaluation
- Multilevel modeling
- Bayesian hierarchical modeling
- Endogeneity and identification challenges
- Mediation models and causal inference
- Exploratory analyses
- Data wrangling


## Things I Am Not Very Good At...

- Crafting a "theoretical contribution"
- Identifying a "theoretical gap"
- Motivating a "theoretical gap"


## Workflow

- R (preferred) or Stata
- Slack
- GitHub and markdown
- Google Docs
- Transparency and reproducibility
- Timeliness and expectation management

